/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zakalwe.gameoflife;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class GameOfLifeArraysTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
