/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zakalwe.gameoflife;

import org.testng.annotations.*;
import com.zakalwe.gameoflife.arrays.GameOfLifeArrays;
import static org.testng.Assert.*;

public class GameOfLifeArraysTest {

    // Rules:
    // 1. Any live cell with two or three live neighbours survives.
    // 2. Any dead cell with three live neighbours becomes a live cell.
    // 3. All other live cells die in the next generation. Similarly, all other dead cells stay dead.
    

    @Test public void testTwoOrThreeSurvives() {
        final int xmax = 6;
        final int ymax = 6;
        final GameOfLifeArrays gameOfLifeArrays = new GameOfLifeArrays(xmax, ymax);

        // set a 2x2 square of live cells
        gameOfLifeArrays.setCell(1, 1, true);
        gameOfLifeArrays.setCell(2, 1, true);
        gameOfLifeArrays.setCell(1, 2, true);
        gameOfLifeArrays.setCell(2, 2, true);
        gameOfLifeArrays.print();
        assertEquals(gameOfLifeArrays.count(), 4);

        gameOfLifeArrays.progress();
        gameOfLifeArrays.print();
        assertEquals(gameOfLifeArrays.count(), 4);

        // check row above square
        assertFalse(gameOfLifeArrays.getCell(0, 0));
        assertFalse(gameOfLifeArrays.getCell(1, 0));
        assertFalse(gameOfLifeArrays.getCell(2, 0));
        assertFalse(gameOfLifeArrays.getCell(3, 0));

        // check row below square
        assertFalse(gameOfLifeArrays.getCell(0, 3));
        assertFalse(gameOfLifeArrays.getCell(1, 3));
        assertFalse(gameOfLifeArrays.getCell(2, 3));
        assertFalse(gameOfLifeArrays.getCell(3, 3));

        // check left and right of square
        assertFalse(gameOfLifeArrays.getCell(0, 1));
        assertFalse(gameOfLifeArrays.getCell(0, 2));
        assertFalse(gameOfLifeArrays.getCell(3, 1));
        assertFalse(gameOfLifeArrays.getCell(3, 2));

        // 2x2 square of live cells is stable and should never change
        for (int i = 0; i < 101; i++){ 
            gameOfLifeArrays.progress();
            assertEquals(gameOfLifeArrays.count(), 4);
        }
        gameOfLifeArrays.print();
        assertEquals(gameOfLifeArrays.count(), 4);
    }
}
