# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      working-directory: ./python3
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting with Black
      working-directory: ./python3
      run: |
        black --check game_of_life.py gameoflife tests
    - name: Check types with mypy
      working-directory: ./python3
      run: |
        mypy --strict --no-warn-unused-ignores game_of_life.py gameoflife tests
    - name: Test with pytest
      working-directory: ./python3
      run: |
        python -m pytest -v --cov --cov-report=xml --cov-branch --cov-report term-missing
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)